version: '3.1'
services:
  redis:
    image: "redis"
    volumes:
     - /utils/opt/redis/data:/data
     - /utils/opt/redis/etc/redis.conf:/etc/redis.conf
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    volumes:
      - /utils/database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

